### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by dinkco** [typesettin/periodicjs#95]
I'm getting the following error on new installation:

```
configuration log Tue Jan 06 2015 22:55:28 GMT+0100 (CET)- 
 creating admin user
Invalid extension installation: periodicjs.ext.admin
 ====!!ERROR!!====
```
Any ideas on how to fix it?

**Comment by yawetse** [comment]
can you give me some more info about the environment you’re installing it on? is this locally on your machine? what kind of machine is it?

also any idea on what version of periodic you’re installing?

**Comment by ginmartini** [comment]
Sorry, should have mantioned it up front.

It's my local Linux Mint 17.1 64-bit
Periodicjs version 4.1.0 (fresh install few minutes ago)

Sorry, I'm new to node and development in general, so I may 
not provide all the info you need. Either way, I have installed and 
run other node apps on my current machine without problems, so this 
is weird.

**Comment by ginmartini** [comment]
Hey, no problem -- thanks for sharing periodic with us. Once I get comfortable with it I will try to contribute to it as well, maybe even documentation.

As an aside, is there a list of app people have build with periodicjs thus far? Just curious I guess.

Ok, I'm closing the issue for now. Thank you!

**Comment by yawetse** [comment]
there isn't a public one, it's been used on two enterprise projects so far, if you DM me I can let you know which companies are currently using it.

one is a back end for a mobile app, that's integrated with an NFC band and and android app. another is a repository for financial data.

I'm personally working on two projects that are more consumer facing, and then will work on 1) the project page for periodic and 2 a list of public apps that are using it.

**Comment by ginmartini** [comment]
Thank you, I will DM you.
